stages:
  - build
  - test
  # - report

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/*
    - cache/Cypress
    - node_modules
    - build

INSTALL:
  image: cypress/browsers:node18.12.0-chrome107
  stage: build
  script:
    - npm ci

RUN:
  image: cypress/browsers:node18.12.0-chrome107
  stage: test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm start &
    # run Cypress tests
    - npx cypress run

# REPORT:
#   image: cypress/browsers:node18.12.0-chrome107
#   stage: report
#   script:
#     # Generate Mochawesome report
#     - npm run merge-report
#     - npm run marge-report
#   when: always
#   only:
#     - develop
#   artifacts:
#     expire_in: 10 days
#     when: always
#     paths:
#       - cypress/screenshots